# nets_ingest_pdf.R — extract survey-report PDFs locally and prepare a redacted copy that
# an AI agent may read.
#
# Usage:
#   Rscript nets_ingest_pdf.R <survey_dir> [--ocr] [--force]
#
# For every PDF in <survey_dir>/sources/reports/ this writes:
#   local/<doc>/fulltext.md      full text with page markers. LOCAL ONLY — agents must not read.
#   context/<doc>.md             redacted text: coordinates masked, station listings withheld.
#   context/<doc>.index.md       headings and table/figure captions by page, for navigation.
#   context/redaction-log.csv    per-page counts (never the masked values themselves).
#   sources/register.csv         file checksums, so later syntheses can cite what they used.
#
# Only counts and paths are printed to the console, never report content.

if (!exists("nets_read_manifest", mode = "function")) {
  local({
    self <- NULL
    for (i in rev(seq_len(sys.nframe()))) {
      of <- sys.frame(i)$ofile
      if (!is.null(of)) { self <- of; break }
    }
    if (is.null(self)) self <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])
    source(file.path(dirname(normalizePath(self)), "nets_common.R"))
  })
}

# Headings (numbered or upper-case lines) and captions in English, French, Portuguese
# and Spanish, which covers most EAF-Nansen survey reports.
nets_caption_regex <- regex(
  "^\\s*(table|tableau|tabela|tabla|figure|figura|fig\\.|annex|annexe|anexo|appendix|appendice)\\s*[A-Z]?[0-9IVX]+",
  ignore_case = TRUE
)
nets_heading_regex <- "^\\s*(\\d{1,2}(\\.\\d{1,2}){0,3})\\.?\\s+([A-Z\u00C0-\u00DE][^|]{2,90})$"

nets_page_outline <- function(text) {
  lines <- str_split(text, "\n")[[1]] |> str_trim()
  lines <- lines[nzchar(lines)]
  captions <- lines[str_detect(lines, nets_caption_regex)]
  headings <- lines[str_detect(lines, nets_heading_regex) & !str_detect(lines, "\\s{3,}\\S")]
  upper <- lines[str_detect(lines, "^[A-Z\u00C0-\u00DE][A-Z\u00C0-\u00DE ,&'/-]{3,60}$")]
  unique(c(headings, upper, captions)) |> str_trunc(110)
}

nets_ingest_one <- function(pdf, survey_dir, m, ocr = FALSE) {
  slug <- nets_slug(tools::file_path_sans_ext(basename(pdf)))
  red_cfg <- m$redaction %||% list()
  keep_whole <- red_cfg$keep_whole_degree_mentions %||% TRUE
  threshold <- red_cfg$withhold_threshold %||% 6L
  manual_withhold <- nets_parse_pages(red_cfg$withhold_pages[[basename(pdf)]])
  manual_release <- nets_parse_pages(red_cfg$release_pages[[basename(pdf)]])

  pages <- pdftools::pdf_text(pdf)
  n <- length(pages)
  low_text <- nchar(str_squish(pages)) < 40
  ocr_done <- rep(FALSE, n)
  if (ocr && any(low_text)) {
    if (requireNamespace("tesseract", quietly = TRUE)) {
      idx <- which(low_text)
      pages[idx] <- pdftools::pdf_ocr_text(pdf, pages = idx)
      ocr_done[idx] <- TRUE
    } else {
      message("  --ocr requested but the 'tesseract' R package is not installed; skipped.")
    }
  }

  # Full text stays on this machine, outside the agent-readable folder.
  local_dir <- file.path(survey_dir, "local", slug)
  dir.create(local_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(
    c(paste0("<!-- LOCAL ONLY. Unredacted text of ", basename(pdf), ". AI agents must not read this file. -->"),
      map2_chr(seq_len(n), pages, ~ paste0("\n--- PDF page ", .x, " ---\n", .y))),
    file.path(local_dir, "fulltext.md"), useBytes = TRUE
  )

  score <- map_int(pages, nets_position_score)
  auto_withhold <- score >= threshold & !(seq_len(n) %in% manual_release)
  withheld <- auto_withhold | seq_len(n) %in% manual_withhold
  reason <- case_when(
    seq_len(n) %in% manual_withhold ~ "listed in survey.yaml redaction$withhold_pages",
    auto_withhold ~ paste0("looks like a station/position listing (score ", score, ")"),
    TRUE ~ ""
  )
  red <- nets_redact_text(pages, keep_whole_degree = keep_whole)

  body <- map_chr(seq_len(n), function(i) {
    content <- if (withheld[i]) {
      paste0("[Page withheld from agent context: ", reason[i], ". ",
             "The original is available locally to the user.]")
    } else if (low_text[i] && !ocr_done[i]) {
      "[No text layer on this page (scanned image?). Re-run ingestion with --ocr, or read it yourself.]"
    } else {
      red$text[i]
    }
    paste0("\n--- PDF page ", i, " ---\n", content)
  })
  header <- c(
    paste0("# ", basename(pdf), " \u2014 agent context copy (redacted)"),
    "",
    paste0("Survey ", m$survey_id, " \u00B7 report status: ", m$report_status,
           " \u00B7 context policy: ", m$context_policy),
    paste0("Pages: ", n, " \u00B7 withheld: ", sum(withheld),
           " \u00B7 coordinates masked: ", sum(red$n[!withheld]),
           " \u00B7 pages without text: ", sum(low_text & !ocr_done)),
    paste0("Generated by NETS ", nets_version(), " on ", Sys.Date(), ". ",
           "Page numbers are PDF page indices, not printed page numbers."),
    "Extraction can garble tables. Every value used in a synthesis must be checked against the original PDF.",
    ""
  )
  context_dir <- file.path(survey_dir, "context")
  dir.create(context_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(c(header, body), file.path(context_dir, paste0(slug, ".md")), useBytes = TRUE)

  outline <- map(seq_len(n), ~ nets_page_outline(red$text[.x]))
  index <- c(
    paste0("# Index of ", basename(pdf)), "",
    "Headings and captions detected per PDF page (redacted). Use it to decide which pages to read.", "",
    "| Page | Status | Headings and captions |", "|---:|---|---|",
    map_chr(seq_len(n), function(i) {
      status <- if (withheld[i]) "withheld" else if (low_text[i] && !ocr_done[i]) "no text" else "available"
      paste0("| ", i, " | ", status, " | ",
             str_replace_all(paste(outline[[i]], collapse = " \u00B7 "), "\\|", "/"), " |")
    })
  )
  writeLines(index, file.path(context_dir, paste0(slug, ".index.md")), useBytes = TRUE)

  list(
    register = tibble(
      document = basename(pdf), slug = slug, md5 = unname(tools::md5sum(pdf)), pages = n,
      pages_without_text = sum(low_text & !ocr_done), pages_withheld = sum(withheld),
      coordinates_masked = sum(red$n[!withheld]), ingested_on = as.character(Sys.Date()),
      nets_version = nets_version()
    ),
    log = tibble(
      document = basename(pdf), page = seq_len(n), characters = nchar(pages),
      position_score = score, coordinates_masked = red$n, withheld = withheld,
      reason = reason, ocr = ocr_done
    )
  )
}

nets_ingest_reports <- function(survey_dir, ocr = FALSE, force = FALSE) {
  m <- nets_read_manifest(survey_dir)
  if (identical(m$context_policy, "local-only")) {
    message("Note: context_policy is 'local-only'. The redacted copies are written, but an ",
            "agent using a cloud model must not read them for this survey.")
  }
  pdfs <- list.files(file.path(survey_dir, "sources", "reports"), pattern = "\\.pdf$",
                     ignore.case = TRUE, full.names = TRUE)
  if (!length(pdfs)) stop("No PDFs found in ", file.path(survey_dir, "sources", "reports"), call. = FALSE)

  reg_file <- file.path(survey_dir, "sources", "register.csv")
  log_file <- file.path(survey_dir, "context", "redaction-log.csv")
  old_reg <- if (file.exists(reg_file)) read_csv(reg_file, show_col_types = FALSE, col_types = cols(.default = "c")) else NULL
  old_log <- if (file.exists(log_file)) read_csv(log_file, show_col_types = FALSE, col_types = cols(.default = "c")) else NULL

  results <- list()
  for (pdf in pdfs) {
    md5 <- unname(tools::md5sum(pdf))
    unchanged <- !is.null(old_reg) && any(old_reg$document == basename(pdf) & old_reg$md5 == md5)
    if (unchanged && !force) {
      message("Unchanged, skipped: ", basename(pdf), " (use --force to redo)")
      next
    }
    message("Ingesting: ", basename(pdf))
    results[[basename(pdf)]] <- nets_ingest_one(pdf, survey_dir, m, ocr = ocr)
    r <- results[[basename(pdf)]]$register
    message("  pages ", r$pages, " \u00B7 withheld ", r$pages_withheld,
            " \u00B7 coordinates masked ", r$coordinates_masked,
            " \u00B7 without text ", r$pages_without_text)
  }
  if (!length(results)) return(invisible(NULL))

  done <- names(results)
  reg <- bind_rows(
    if (!is.null(old_reg)) filter(old_reg, !document %in% done),
    map_dfr(results, "register") |> mutate(across(everything(), as.character))
  )
  lg <- bind_rows(
    if (!is.null(old_log)) filter(old_log, !document %in% done),
    map_dfr(results, "log") |> mutate(across(everything(), as.character))
  )
  write_csv(reg, reg_file)
  write_csv(lg, log_file)
  message("Agent-readable copies are in ", file.path(survey_dir, "context"),
          ". Review the redaction log before starting a synthesis.")
  invisible(reg)
}

if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  if (!length(args) || args[1] %in% c("-h", "--help")) {
    cat("Usage: Rscript nets_ingest_pdf.R <survey_dir> [--ocr] [--force]\n")
    quit(status = if (length(args)) 0 else 1)
  }
  nets_ingest_reports(args[1], ocr = "--ocr" %in% args, force = "--force" %in% args)
}
